/**
 * Cryptographic authentication module utilizing Web Crypto API.
 * Ensures zero secret leakage, timing-attack resistance, and key rotation support.
 */

const encoder = new TextEncoder();

/**
 * Constant-time equality comparison for two strings of identical or differing lengths.
 * Prevents timing side-channel attacks on cryptographic signatures.
 */
export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) {
    return false;
  }
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

/**
 * Imports a raw string secret into a Web Crypto HMAC CryptoKey.
 */
async function importHmacKey(secret: string): Promise<CryptoKey> {
  return await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"]
  );
}

/**
 * Computes hexadecimal HMAC-SHA256 of the given message string.
 */
export async function computeHmacHex(secret: string, message: string): Promise<string> {
  const key = await importHmacKey(secret);
  const signatureBytes = await crypto.subtle.sign("HMAC", key, encoder.encode(message));
  const hashArray = Array.from(new Uint8Array(signatureBytes));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Verifies a signed stream URL from Stremio.
 * URL format generated by backend:
 *   /dl/{token}/{file_id}/{name}?e={exp}&s={sig}
 * where:
 *   sig = HMAC_SHA256(secret, "/dl/{token}/{file_id}:{exp}")[:32]
 *
 * Supports secret rotation via optional previousSecret.
 */
export async function verifyStreamSignature(
  secret: string,
  prevSecret: string | undefined,
  token: string,
  fileId: string,
  exp: number,
  sig: string
): Promise<{ valid: boolean; reason?: string }> {
  if (!secret) {
    return { valid: false, reason: "Worker SHARED_SECRET is not configured" };
  }
  if (!sig || sig.length < 16) {
    return { valid: false, reason: "Missing or truncated signature" };
  }
  if (typeof exp !== "number" || isNaN(exp)) {
    return { valid: false, reason: "Invalid expiration timestamp" };
  }

  const nowSeconds = Math.floor(Date.now() / 1000);
  if (exp < nowSeconds) {
    return { valid: false, reason: "Stream URL signature has expired" };
  }

  const signedMessage = `/dl/${token}/${fileId}:${exp}`;

  // Check against current secret
  const expectedSigCurrent = (await computeHmacHex(secret, signedMessage)).slice(0, 32);
  if (timingSafeEqual(expectedSigCurrent, sig.slice(0, 32))) {
    return { valid: true };
  }

  // Check against previous secret if during rotation
  if (prevSecret) {
    const expectedSigPrev = (await computeHmacHex(prevSecret, signedMessage)).slice(0, 32);
    if (timingSafeEqual(expectedSigPrev, sig.slice(0, 32))) {
      return { valid: true };
    }
  }

  return { valid: false, reason: "Signature mismatch" };
}

/**
 * Creates authentication headers for Worker-to-Backend requests (/api/cf/config, /api/cf/usage).
 * Backend expects:
 *   x-cf-time: unix_timestamp_string
 *   x-cf-sig: HMAC_SHA256(secret, "{ts}\n{method} {path}\n{body}")
 */
export async function signWorkerRequest(
  secret: string,
  method: string,
  path: string,
  bodyText: string = ""
): Promise<{ "x-cf-time": string; "x-cf-sig": string }> {
  const ts = Math.floor(Date.now() / 1000).toString();
  const stringToSign = `${ts}\n${method.toUpperCase()} ${path}\n${bodyText}`;
  const sig = await computeHmacHex(secret, stringToSign);
  return {
    "x-cf-time": ts,
    "x-cf-sig": sig,
  };
}

/**
 * Verifies an incoming Backend-to-Worker request (e.g. POST /api/sync).
 * Ensures clock skew is within 300 seconds and validates signature.
 */
export async function verifyBackendRequest(
  secret: string,
  prevSecret: string | undefined,
  method: string,
  path: string,
  bodyText: string,
  ts: string,
  sig: string
): Promise<boolean> {
  if (!secret || !ts || !sig) {
    return false;
  }

  const timeNum = parseInt(ts, 10);
  if (isNaN(timeNum)) {
    return false;
  }

  const nowSeconds = Math.floor(Date.now() / 1000);
  if (Math.abs(nowSeconds - timeNum) > 300) {
    return false; // Skew exceeds 5 minutes
  }

  const stringToSign = `${ts}\n${method.toUpperCase()} ${path}\n${bodyText}`;

  const expectedCurrent = await computeHmacHex(secret, stringToSign);
  if (timingSafeEqual(expectedCurrent, sig)) {
    return true;
  }

  if (prevSecret) {
    const expectedPrev = await computeHmacHex(prevSecret, stringToSign);
    if (timingSafeEqual(expectedPrev, sig)) {
      return true;
    }
  }

  return false;
}
